subscription_id     = "ed694d74-dc45-4cf9-9174-69a0cf39186f"
resource_group_name = "rg-psynaps-dev"
location            = "Japan East"
vnet_name           = "vnet-psynaps-prd"
environment         = "Development"
