subscription_id = "0a8ea8c9-e4f9-480e-9e1d-ef3315581cc2"
#resource_group_name = "rg-psynaps-dev"
#location            = "Japan East"
#vnet_name           = "vnet-psynaps-prd"
#environment = "Development"
